name: Watch Edit Releases and Build Packages

on:
  schedule:
    - cron: '0 0 * * *'    # Daily at midnight UTC
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.compare.outputs.new_version }}
      is_new:       ${{ steps.compare.outputs.is_new }}
    steps:
      - name: Fetch latest upstream release tag
        id: fetch
        run: |
          echo "latest_tag=$(curl -s https://api.github.com/repos/microsoft/edit/releases/latest \
            | jq -r .tag_name)" >> $GITHUB_OUTPUT

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compare with existing tags
        id: compare
        run: |
          latest="${{ steps.fetch.outputs.latest_tag }}"
          if git rev-parse "refs/tags/$latest" >/dev/null 2>&1; then
            echo "is_new=false" >> $GITHUB_OUTPUT
          else
            echo "is_new=true" >> $GITHUB_OUTPUT
            echo "new_version=$latest" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-release
    if: needs.check-release.outputs.is_new == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64: use upstream binary
          - os: ubuntu-latest
            arch: x86_64
            pkg: deb
            pkg_arch: amd64
            prefix: /usr/bin
            source: false
          # Linux aarch64: use upstream binary
          - os: ubuntu-latest
            arch: aarch64
            pkg: deb
            pkg_arch: arm64
            prefix: /usr/bin
            source: false
          # macOS Apple Silicon: build from source
          - os: macos-latest
            arch: aarch64-apple-darwin
            pkg: osxpkg
            pkg_arch: arm64
            prefix: /usr/local/bin
            source: true

    env:
      VERSION: ${{ needs.check-release.outputs.new_version }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install packaging tools
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y ruby-dev build-essential zstd jq
            sudo gem install --no-document fpm
          else
            brew install ruby
            gem install --no-document fpm
          fi

      - name: Prepare binary
        run: |
          version="${VERSION#v}"
          mkdir -p stage${{ matrix.prefix }}
          if [ "${{ matrix.source }}" = "true" ]; then
            git clone --depth 1 --branch "${VERSION}" https://github.com/microsoft/edit.git upstream
            cd upstream
            rustup default nightly
            rustup target add ${{ matrix.arch }}
            cargo build --release --target ${{ matrix.arch }}
            cp target/${{ matrix.arch }}/release/edit \
               ../stage${{ matrix.prefix }}/
          else
            url="https://github.com/microsoft/edit/releases/download/${VERSION}/edit-${version}-${{ matrix.arch }}-linux-gnu.tar.zst"
            curl -L -o edit.tar.zst "$url"
            mkdir -p stage/usr/bin
            tar --use-compress-program=unzstd -xf edit.tar.zst
            mv edit stage/usr/bin/edit
            chmod +x stage/usr/bin/edit
          fi

      - name: Package
        run: |
          version="${VERSION#v}"
          if [[ "${{ matrix.pkg }}" == "deb" ]]; then
            fpm -s dir -t deb \
                -n edit \
                -v "$version" \
                --architecture "${{ matrix.pkg_arch }}" \
                --prefix /usr \
                --description "Microsoft Edit CLI editor" \
                --maintainer "automated@github.actions" \
                -C stage usr/bin/edit
            mv edit_*.deb edit-${version}-${{ matrix.pkg_arch }}.deb
          else
            fpm -s dir -t osxpkg \
                -n edit \
                -v "$version" \
                --architecture "${{ matrix.pkg_arch }}" \
                --prefix "${{ matrix.prefix }}" \
                --description "Microsoft Edit CLI editor" \
                --maintainer "automated@github.actions" \
                -C stage "${{ matrix.prefix }}/edit"
            mv edit-*.pkg edit-${version}-${{ matrix.pkg_arch }}.pkg
          fi

      - name: Generate SHA256 checksum
        run: |
          ext=$( [[ "${{ matrix.pkg }}" == "deb" ]] && echo deb || echo pkg )
          for file in edit-*."$ext"; do
            sha256sum "$file" > "$file".sha256
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edit-${{ matrix.pkg }}-${{ matrix.pkg_arch }}
          path: |
            edit-*.$( [[ "${{ matrix.pkg }}" == "deb" ]] && echo deb || echo pkg )
            *.sha256

  release:
    needs: [check-release, build]
    if: needs.check-release.outputs.is_new == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Flatten artifacts
        run: |
          find all-artifacts -type f -exec mv {} all-artifacts/ \;

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "${{ needs.check-release.outputs.new_version }}"
          git push origin "${{ needs.check-release.outputs.new_version }}"

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-release.outputs.new_version }}
          name: "Edit ${{ needs.check-release.outputs.new_version }}"
          files: all-artifacts/*.deb,all-artifacts/*.pkg,all-artifacts/*.sha256
